name: flutter_simple_app
description: A new Flutter project.

dependencies:
  ktoast: ^0.0.2
  banner_view: ^1.1.2
  flutter_html_view: "^0.5.3"
  flutter_search_bar: ^2.0.5
  barcode_scan: ^0.0.4
  map_view: ^0.0.14
  shared_preferences: ^0.4.2
  path_provider: ^0.4.1
  url_launcher: ^3.0.3
  image_picker: ^0.4.6
  sqflite: any
  firebase_database: ^1.0.3
  video_player: ^0.5.2
  connectivity: ^0.3.1
  device_info: ^0.2.1
  flutter_webview_plugin: ^0.2.0
  share: ^0.5.2
  flutter_staggered_grid_view: ^0.2.2
  event_bus: ^1.0.1
  flutter_advanced_networkimage: any
  multi_image_picker: ^1.0.51
  photo_view: ^0.0.4
  flutter_slidable: ^0.4.0
  pull_to_refresh: ^1.1.5
  flutter_cupertino_settings: ^0.0.8
  flutter_cupertino_date_picker: ^0.0.4
  flutter_downloader: ^0.0.7
  small_calendar: ^0.4.0
  fluttertoast: ^2.0.7
  flutter_duration_picker: "^1.0.0"
  flutter_web_view: ^0.0.2
#  flutter_image_pick_crop: ^0.0.1
#  flutter_multiple_image_picker: ^0.0.1
  flutter:
    sdk: flutter
  flutter_walkthrough:
#  flutter_multiple_image_picker:


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  english_words: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - data_repo/img/ic_launcher.png
    - data_repo/img/social/facebook.png
    - data_repo/img/social/instagram.png
    - data_repo/img/social/google_plus.png
    - data_repo/img/social/linkedin.png
    - data_repo/img/social/twitter.png
    - data_repo/img/bg1.jpg
    - data_repo/img/banner1.jpg
    - data_repo/img/banner2.jpg
    - data_repo/img/banner3.jpg
    - data_repo/img/banner4.jpg
    - data_repo/img/talk_casually.png
    - data_repo/starwars_data.json
